### ISSUE TITLE
Orocos RTT 2.8 - Compiling Error with Boost

### ISSUE THREAD

**Issue by thachdd88** [orocos-toolchain/rtt#168]
Hi everybody,

While compiling Orocos RTT, I encountered an error that I do not know how to fix. 

```
user@NRMKStep-PC:~/dev/orocos/orocos-2.8/build/rtt$ make
[  0%] Building CXX object rtt/CMakeFiles/orocos-rtt-gnulinux_dynamic.dir/Operation.cpp.o
[  0%] Building CXX object rtt/CMakeFiles/orocos-rtt-gnulinux_dynamic.dir/FactoryExceptions.cpp.o
[  1%] Building CXX object rtt/CMakeFiles/orocos-rtt-gnulinux_dynamic.dir/ConfigurationInterface.cpp.o
In file included from /home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/DataSourceTypeInfo.hpp:44:0,
                 from /home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/DataSource.inl:5,
                 from /home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/DataSource.hpp:237,
                 from /home/user/dev/orocos/orocos-2.8/build/rtt/rtt/Attribute.hpp:42,
                 from /home/user/dev/orocos/orocos-2.8/build/rtt/rtt/ConfigurationInterface.hpp:44,
                 from /home/user/dev/orocos/orocos-2.8/build/rtt/rtt/ConfigurationInterface.cpp:40:
/home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/../types/carray.hpp:99:48: error: expected ‘)’ before ‘<’ token
/home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/../types/carray.hpp:165:41: error: ‘array’ is not a member of ‘boost::serialization’
/home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/../types/carray.hpp:165:41: note: suggested alternative:
/usr/local/include/boost/array.hpp:60:11: note:   ‘boost::array’
/home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/../types/carray.hpp:165:75: error: expected primary-expression before ‘>’ token
/home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/../types/carray.hpp:165:77: error: expected primary-expression before ‘const’
/home/user/dev/orocos/orocos-2.8/build/rtt/rtt/internal/../types/carray.hpp:165:89: error: declaration of ‘operator=’ as non-function
make[2]: *** [rtt/CMakeFiles/orocos-rtt-gnulinux_dynamic.dir/ConfigurationInterface.cpp.o] Error 1
make[1]: *** [rtt/CMakeFiles/orocos-rtt-gnulinux_dynamic.dir/all] Error 2
make: *** [all] Error 2
```

I seemed to me that there was something wrong between RTT and Boost. Also, I tried many Boost versions but the errors were same.

I really appreciate if somebody can give me an advice how to solve my problem.

Thank you.

**Comment by meyerj** [comment]
That's strange. `boost::serialization::array<T>` is defined in the header `boost/serialization/array.hpp` included from [carray.hpp:42](https://github.com/orocos-toolchain/rtt/blob/toolchain-2.8/rtt/types/carray.hpp#L42) and apparently your compiler is not complaining about a missing header. 

Could you please add some more details about your build environment, in particular the OS, compiler, Boost versions you already tried and which branch of rtt you are building? I assume you do not have a standard Boost installation from your distro's package repository if you write that you tried different versions?

**Comment by DhruvKoolRajamani** [comment]
Did it work? Did you find the fix?

**Comment by meyerj** [comment]
This might be related to the renaming of `boost::serialization::array` to `boost::serialization::array_wrapper` in Boost 1.61 (https://github.com/boostorg/serialization/commit/e3b67eb299b070edb32c2eb5da76653b4ed9cf5e). The respective patch in RTT master (https://github.com/orocos-toolchain/rtt/commit/87659188c71bf3013247590a386321648dd8fb67) has not been backported to toolchain-2.8, so that version only compiles with Boost 1.60 and below. Ubuntu Trusty comes with Boost 1.54, which is probably the most commonly used platform and version for toolchain-2.8.

Building and using a non-default version of Boost from source is possible, but there are some pitfalls. You have to make sure to use the headers of the custom version only (e.g. by uninstalling all `libboost-.*-dev` packages) and to not link with any other library that has been built against a different version of Boost (e.g. in combination with ROS libraries installed from debs).
