### ISSUE TITLE
orocos with imcompatiable gcc version (7.4)

### ISSUE THREAD

**Issue by KenanNiu** [orocos-toolchain/rtt#316]
I have gcc version 7.4 and successfully installed ROS kinetic and orocos via Synaptic. I figured out, that when I catkin_make my catkin workplace, it cannot link ros-rtt. 
I have tested, gcc/g++ 7.4 , gcc/g++ 4.8. It only works when i switched gcc/g++ 5(.5). If you have this problem. Maybe firstly check you gcc version. 
Still, it would be good to know why it happened?
Kenan

**Comment by meyerj** [comment]
The compatibility with GCC 5 and newer has been fixed in https://github.com/orocos-toolchain/rtt/pull/200 in 2017, by removing the version check completely.

Depending on which version you tried to build from source, it may not yet have included this patch. The last version released into ROS Kinetic was [v2.9.2](https://github.com/orocos-toolchain/rtt/releases) in June 2019, but we did not cherry-pick #200 for some reason although it is older. The commits picked for [v2.9.1](https://github.com/orocos-toolchain/rtt/releases) and [v2.9.2](https://github.com/orocos-toolchain/rtt/releases) have been carefully selected to not break the ABI.
